//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCours
    {
        public int EmployeeCourseId { get; set; }
        public int CourseId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
