//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpQualification
    {
        public int EmpQualificationId { get; set; }
        public int QualificationId { get; set; }
        public int YearOfPassing { get; set; }
        public Nullable<decimal> Aggrigate { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
