//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmpQualifications = new HashSet<EmpQualification>();
            this.ProfilePics = new HashSet<ProfilePic>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int GenderId { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public int StatusTypeId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<EmpQualification> EmpQualifications { get; set; }
        public virtual ICollection<ProfilePic> ProfilePics { get; set; }
    }
}
